### ISSUE TITLE
Highlighting unpaired quotes

### ISSUE THREAD

**Issue by mbaas2** [bhank/vscode-bad-code-highlighter#1]
My typical fault (after intense editing) is to end with a line of code that somewhere has an unmatched quote-character - so I thought this would be the best tool to highlight such cases.
But I can't get it to work - could you pls. have a look?

Here's my config:
```
    {
        "filename": "\\.mipage$",
        "text": "\\"[^\\"]*$",
        "color": "red",
        "tooltip": "Qoutes not paired!"
    }
```

**Comment by bhank** [comment]
Since my extension's code is not using the `m` modifier on the regex, `^` and `$` will only match at the beginning and end of the entire file, which makes it hard to anchor to a single line.

This line: `"text": "\\"[^\\"]*$",` is invalid json; quotes don't need to be escaped in a regex, but they do need to be escaped in json, so you need just a single backslash before each of them. But even with that fixed, that regex just matches the last quote in the file (because the `$` at the end matches only the end of the file).

My first attempt to match unpaired quotes was this. (I used a regex from [a Stack Overflow answer](https://stackoverflow.com/a/16863999/2076576).)
```
    {
        "filename": "\\.mipage$",
        "text": "^[^\"]*(?:[^\"]*\"[^\"]*\")*[^\"]*\"[^\"]*$",
        "color": "red",
        "tooltip": "The file contains an unpaired quote... somewhere."
    }
```
It's pretty ugly, and as the tooltip implies, it highlights the entire file rather than the line with unpaired quotes on it.

My second attempt anchors it using end-of-line characters (`\n`, optionally preceded by `\r`), so it will highlight the affected lines:
```
    {
        "filename": "\\.mipage$",
        "text": "(^|\\r?\\n)[^\\n\"]*\"(?:[^\\n\"]*\"[^\\n\"]*\")*[^\\n\"]*(\\r?\\n|$)",
        "color": "red",
        "tooltip": "There's an unpaired quote on this line!"
    }
```
It's still pretty ugly, but appears to work OK.

**Comment by mbaas2** [comment]
Thanks! Works nicely :)
